### ISSUE TITLE
TextViewScrollbar is wrongly updating RightOffset and BottomOffset.

### ISSUE THREAD

**Issue by BDisp** [chr1st0scli/RainLispConsole#6]
Since you are initializing `TextViewScrollbar` by calling  `base(textView, true)` then the `VisibleChanged` event should handle the `BottomOffset` (is the vertical bar) and the `OtherScrollBarView.VisibleChanged` should be handle the `RightOffset` (is the horizontal bar). You are doing the opposite.

**Comment by chr1st0scli** [comment]
Hi @BDisp, thank you for your feedback.

If this relates to the bug I opened in terminal.gui, I tried your suggestion but with no luck.

Notice that the code that you describe, I took it as is from Editor.cs from the scenarios folder, lines 149 - 163. The scrollbar view is also initialized with ` new ScrollBarView (_textView, true);` there too.

**Comment by BDisp** [comment]
Sorry @chr1st0scli I had mislead myself. When the vertical bar becomes invisible there is more horizontal space and is the `RightOffset` that must be set. When the horizontal bar becomes invisible there is more vertical space and is the `BottomOffset` that must be set. So it's right, sorry. I almost finishing the fix for your submitted issue and also found that the paste isn't rendering the screen. Maybe today I'll submit a PR.
